### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Xiaoxiang140** [CubeWhyMC/celestial#1]
[14:38:28] [Genesis/INFO] Launching Minecraft 1.8.9 v1_8 (parsed from 1.8.9)
[14:38:28] [Genesis/INFO] Found external file: OptiFine_v1_8-legacy.jar
[14:38:28] [IchorPipeline/INFO] Creating pipeline for v1_8 with [ALL, PRE_INIT, PRE_FORGE_PATCH, FORGE_PATCH, POST_FORGE_PATCH, PRE_OPTIFINE_PATCH, OPTIFINE_PATCH, POST_OPTIFINE_PATCH, INIT, INITIAL_REMAP, EXTERNAL_REMAP, PRE_META_MIXIN, META_MIXIN, POST_META_MIXIN, PRE_LUNAR_MIXIN, LUNAR_MIXIN, POST_LUNAR_MIXIN, PRE_EXTERNAL_MIXIN, EXTERNAL_MIXIN, POST_EXTERNAL_MIXIN, OBFUSCATION, FINAL]
[14:38:28] [IchorPipeline/INFO] attempting to load IchorModules using jdk.internal.loader.ClassLoaders$AppClassLoader@7a81197d
[14:38:28] [IchorPipeline/INFO] found IchorModule com.moonsworth.lunar.ichor.CIHIIHCRORHIIOOCOOOIIOIOO.CRRRRIIOIIRHRRHOICOOHHRIC
[14:38:28] [IchorPipeline/INFO] found IchorModule com.moonsworth.lunar.HIRCRRHCROOCROHCCOCCOHOOR.CRRRRIIOIIRHRRHOICOOHHRIC
[14:38:28] [IchorPipeline/INFO] found IchorModule com.moonsworth.lunar.client.OCHOHCIROIIRRORCHOIICHOHI.HCHHIHRIRCOHRIOROOCIORHCO
[14:38:28] [IchorPipeline/INFO] Found 1 external files and 3 IchorLoaders.
[14:38:28] [IchorPipeline/INFO] Done creating IchorPipeline in 94ms.
[14:38:28] [Genesis/INFO] Found requested jar: C:\Users\Xiaoxiang\.cubewhy\lunarcn\game\OptiFine_v1_8.jar
[14:38:28] [Genesis/INFO] Config hash: 24157098  File hash: 37fbe849
[14:38:28] [Genesis/INFO] Missing class cache: C:\Users\Xiaoxiang\.cubewhy\lunarcn\game\cache\24157098\37fbe849\prebake.cache
[14:38:28] [Genesis/INFO] Prebaking classes...
LUNARCLIENT_STATUS_BUILD_CACHE
[14:38:28] [IchorPipeline/INFO] Loading Mixin runtime for META_MIXIN
[14:38:28] [OptiFine/INFO] Using OptiFine namespace 
[14:38:28] [OptiFine/INFO] Loaded 1050 patches.
[14:38:28] [OptiFine/INFO] Loaded 72 assets.
[14:38:28] [IchorPipeline/WARN] MappingSet for com.moonsworth.lunar.HIRCRRHCROOCROHCCOCCOHOOR.HIOHCCCIOOCRCRROOCICHRRIR.RRIICICHOHRCIIHHCHIHCRICI.HIRCRRHCROOCROHCCOCCOHOOR has 0 field mappings.
IchorClassLoader(META_MIXIN).loadSandboxedMixin: loadedMixin: true loadingMixin: true
com.moonsworth.lunar.ichor.util.FatalIchorError: [IchorClassLoader(POST_OPTIFINE_PATCH)] Failed to remap org/spongepowered/asm/launch/MixinBootstrap
	at com.moonsworth.lunar.ichor.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR.OIHRHORCIORHIIHOHOCRCHHIR.CRRRRIIOIIRHRRHOICOOHHRIC(Unknown Source)
	at com.moonsworth.lunar.ichor.COORORIHIRIOOOCHIIHCRCOOO.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.CIHIIHCRORHIIOOCOOOIIOIOO.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.RIICRROCHOIOCOHHRCRHRHRIH(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.findClass(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.loadClass(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.CIRIHIHOCCHHCRRIOHHCRCOHO(Unknown Source)
	at com.moonsworth.lunar.ichor.CIHIIHCRORHIIOOCOOOIIOIOO.HIRCRRHCROOCROHCCOCCOHOOR(Unknown Source)
	at com.moonsworth.lunar.ichor.HCHHIHRIRCOHRIOROOCIORHCO.CRCIHHHROIIRRHHIOOHORHCRO(Unknown Source)
	at com.moonsworth.lunar.ichor.HCHHIHRIRCOHRIOROOCIORHCO.RIICRROCHOIOCOHHRCRHRHRIH(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.prebake(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.cadixdev.bombe.analysis.asm.ClassProviderInheritanceProvider.provide(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.moonsworth.lunar.ichor.util.CIHIIHCRORHIIOOCOOOIIOIOO.provide(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceProvider$ClassInfo.provideParents(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceProvider$ClassInfo$Impl.provideParents(Unknown Source)
	at org.cadixdev.lorenz.impl.model.AbstractClassMappingImpl.complete(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.lambda$complete$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.COORORIHIRIOOOCHIIHCRCOOO.getCompletedClassMapping(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.COORORIHIRIOOOCHIIHCRCOOO.mapFieldName(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR$CRRRRIIOIIRHRRHOICOOHHRIC.run(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.CCRHHCRRHROIROCCIOCIROOIC(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.run(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR.OIHRHORCIORHIIHOHOCRCHHIR.CRRRRIIOIIRHRRHOICOOHHRIC(Unknown Source)
	... 11 more
Exception in thread "main" com.moonsworth.lunar.ichor.util.FatalIchorError: [IchorClassLoader(POST_OPTIFINE_PATCH)] Failed to remap org/spongepowered/asm/launch/MixinBootstrap
	at com.moonsworth.lunar.ichor.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR.OIHRHORCIORHIIHOHOCRCHHIR.CRRRRIIOIIRHRRHOICOOHHRIC(Unknown Source)
	at com.moonsworth.lunar.ichor.COORORIHIRIOOOCHIIHCRCOOO.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.CIHIIHCRORHIIOOCOOOIIOIOO.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.RIICRROCHOIOCOHHRCRHRHRIH(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.findClass(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.loadClass(Unknown Source)
	at com.moonsworth.lunar.ichor.CRRRRIIOIIRHRRHOICOOHHRIC.CIRIHIHOCCHHCRRIOHHCRCOHO(Unknown Source)
	at com.moonsworth.lunar.ichor.CIHIIHCRORHIIOOCOOOIIOIOO.HIRCRRHCROOCROHCCOCCOHOOR(Unknown Source)
	at com.moonsworth.lunar.ichor.HCHHIHRIRCOHRIOROOCIORHCO.CRCIHHHROIIRRHHIOOHORHCRO(Unknown Source)
	at com.moonsworth.lunar.ichor.HCHHIHRIRCOHRIOROOCIORHCO.RIICRROCHOIOCOHHRCRHRHRIH(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.prebake(Unknown Source)
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.cadixdev.bombe.analysis.asm.ClassProviderInheritanceProvider.provide(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.moonsworth.lunar.ichor.util.CIHIIHCRORHIIOOCOOOIIOIOO.provide(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceProvider$ClassInfo.provideParents(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceProvider$ClassInfo$Impl.provideParents(Unknown Source)
	at org.cadixdev.lorenz.impl.model.AbstractClassMappingImpl.complete(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.lambda$complete$0(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(Unknown Source)
	at org.cadixdev.bombe.analysis.InheritanceCompletable.complete(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.COORORIHIRIOOOCHIIHCRCOOO.getCompletedClassMapping(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.COORORIHIRIOOOCHIIHCRCOOO.mapFieldName(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR$CRRRRIIOIIRHRRHOICOOHHRIC.run(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.CCRHHCRRHROIROCCIOCIROOIC(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.run(Unknown Source)
	at com.moonsworth.lunar.ichor.OIHRHORCIORHIIHOHOCRCHHIR.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR(Unknown Source)
	at com.moonsworth.lunar.ichor.HIOHCCCIOOCRCRROOCICHRRIR.HIOHCCCIOOCRCRROOCICHRRIR.OIHRHORCIORHIIHOHOCRCHHIR.CRRRRIIOIIRHRRHOICOOHHRIC(Unknown Source)
	... 11 more

**Comment by cubewhy** [comment]
请使用JAVA17
暂不支持其他java版本启动
https://azul.com

**Comment by cubewhy** [comment]
也有可能是你的MOD问题
请找 org.cadixdev.bombe.analysis 的开发者解决
