### ISSUE TITLE
lunarCNAPI重定向过多

### ISSUE THREAD

**Issue by misaka10843** [CubeWhyMC/celestial#53]
最新Actions构建中默认使用的https://www.lunarclient.top/api 并不能访问
```log
[INFO] [main] 2024-05-25 11:32:20 Starting connect to the api -> https://lunarclient.top/api
[WARN] [main] 2024-05-25 11:32:25 API is unreachable
[ERROR] [main] 2024-05-25 11:32:25 java.net.ProtocolException: Too many follow-up requests: 21
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.cubewhy.celestial.utils.lunar.LauncherData.metadata(LauncherData.kt:47)
        at org.cubewhy.celestial.CelestialKt.initLauncher(Celestial.kt:283)
        at org.cubewhy.celestial.CelestialKt.run(Celestial.kt:161)
        at org.cubewhy.celestial.CelestialKt.main(Celestial.kt:123)
        at org.cubewhy.celestial.CelestialKt.main(Celestial.kt)
```
![image](https://github.com/CubeWhyMC/celestial/assets/69132853/b3678077-7bf2-4886-adcb-f720f221ebe3)
重定向URL为：https://lunarclient.top/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/https;//github.com/cubewhy

**Comment by cubewhy** [comment]
lccn api is died. RIP!

**Comment by cubewhy** [comment]
lunarclient.top is now redirect to github.com/cubewhy
API is current unreachable, please use `https://api.lunarclientprod.com` inside
